version: '3.1'
services:
  api:
    container_name: api
    build: 
      context: .
    ports:
      - ${SPRING_LOCAL_PORT}:${SPRING_DOCKER_PORT}
    depends_on:
      - db
    env_file:
      - ./.env
    restart: always


  db:
    image: mysql
    ports:
      - ${MYSQLDB_LOCAL_PORT}:${MYSQLDB_DOCKER_PORT}
    environment:
      - MYSQL_DB=${MYSQLDB_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQLDB_ROOT_PASSWORD}
    volumes:
      - tp_achat_data:/var/lib/mysql
    restart: unless-stopped

  adminer:
    image: adminer
    ports:
      - '8081:8080'
    restart: unless-stopped

volumes:
  tp_achat_data:
