---
  - name: playbook
    hosts: localhost
    connection: local
    become : yes
    tasks:
      - name: Add new elements
        xml:
          path: /opt/maven/conf/settings.xml
          xpath: /settings/mirrors/mirror/id
          value: 1
          namespaces:
            m: http://maven.apache.org/SETTINGS/1.0.0
