---
  - name: playbook
    hosts: localhost
    connection: local
    become : yes
    tasks:
      - name: Add new elements
        xml:
          namespaces:
            xmlns: http://maven.apache.org/SETTINGS/1.0.0
          path: /opt/maven/conf/settings.xml
          xpath: /xmlns:settings/xmlns:servers
          attribute: server
          value: hi
