---
- name: prometheus configuration
  hosts: localhost
  connection: local
  tasks:
    - name: add jenkins monitoring to prometheus.yml
      community.docker.docker_container_exec:
        container: prometheus-container
        argv:
          - /bin/bash
          - "tee -a /etc/prometheus/prometheus.yml << EOF

                                  - job_name: jenkins

                                    metrics_path: /prometheus

                                    static_configs:

                                      - targets: ['172.17.0.1:8080']
              EOF"
      register: result

    - name: Print stderr lines
      debug:
        var: result.stderr_lines
