---
- name: Test shell
  hosts: localhost
  gather_facts: no

  tasks:
    - name: Set namespaced
      community.general.xml:
        path: foo.xml
        xpath: /x:settings/servers/server/
        namespaces:
          x: http://maven.apache.org/SETTINGS/1.0.0
