---
  - name: playbook
    hosts: localhost
    become : yes
    tasks:
      - name: update id of the server element
        xml:
          path: /opt/maven/conf/settings.xml
          xpath: /settings/servers/server/id
          value: esprit-devops
      - name: update username of the server element
        xml:
          path: /opt/maven/conf/settings.xml
          xpath: /settings/servers/server/username
          value: auckfmine
      - name: update password of the server element
        xml:
          path: /opt/maven/conf/settings.xml
          xpath: /settings/servers/server/password
          value: aminelol123
