---
  tasks:
    - name: configure maven to push to private nexus repository
      xml:
        become: true
        path: /opt/maven/conf/settings.xml
        xpath: /settings/servers
        value: server
        add_children:
          - id: deploymentRepo
          - username: admin
          - password: aminelol123

