---
  - name: playbook
    hosts: localhost
    connection: local
    become : yes
    tasks:
      - name: Add new elements
        xml:
          namespaces:
            m: http://maven.apache.org/SETTINGS/1.0.0
          path: /opt/maven/conf/settings.xml
          xpath: /m:settings/m:servers
          attribute: server
          value: hi
